apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: mjolnir
      defaultBucket: process_data
      tlsSkipVerify: true
    secureJsonData:
      token: vulnot-super-secret-token
    isDefault: true
